# Generated by Django 3.0.4 on 2020-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='Trash'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.CharField(default='', max_length=40, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='Trash'),
        ),
    ]
