# Generated by Django 3.0.4 on 2020-03-23 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(default='', max_length=200, unique=True, verbose_name='Acoount No')),
                ('balance', models.FloatField(max_length=255, verbose_name='Balance')),
                ('status', models.CharField(default='0', max_length=40, verbose_name='Status')),
                ('trash', models.CharField(default='0', max_length=40, verbose_name='Trash')),
                ('empno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond_fund.TransactionType')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Transaction No')),
                ('amount', models.FloatField(max_length=255, verbose_name='Amount')),
                ('last_balance', models.FloatField(max_length=255, verbose_name='Last Balance')),
                ('current_balance', models.FloatField(max_length=255, verbose_name='Current Balance')),
                ('remark', models.TextField(verbose_name='Remarks')),
                ('clerk', models.CharField(max_length=50, verbose_name='Bond Clerk')),
                ('status', models.CharField(default='0', max_length=40, verbose_name='Status')),
                ('trash', models.CharField(default='0', max_length=40, verbose_name='Trash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond_fund.TransactionType')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Transaction No')),
                ('amount', models.FloatField(max_length=255, verbose_name='Amount')),
                ('remark', models.TextField(default='', verbose_name='Remarks')),
                ('clerk', models.CharField(max_length=50, verbose_name='Bond Clerk')),
                ('status', models.CharField(default='0', max_length=40, verbose_name='Status')),
                ('trash', models.CharField(default='0', max_length=40, verbose_name='Trash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond_fund.Account')),
            ],
        ),
    ]
