# Generated by Django 3.0.4 on 2020-03-21 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=50, verbose_name='Transaction Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Transaction No')),
                ('last_balance', models.FloatField(max_length=255, verbose_name='Last Balance')),
                ('current_balance', models.FloatField(max_length=255, verbose_name='Current Balance')),
                ('amount', models.FloatField(max_length=255, verbose_name='Amount')),
                ('touch_by', models.CharField(max_length=50, unique=True, verbose_name='Touch By')),
                ('status', models.CharField(default='0', max_length=40, verbose_name='Status')),
                ('trash', models.CharField(default='0', max_length=40, verbose_name='Trash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond_fund.TransactionType')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(default='', max_length=200, unique=True, verbose_name='Acoount No')),
                ('balance', models.FloatField(max_length=255, verbose_name='Balance')),
                ('status', models.CharField(default='0', max_length=40, verbose_name='Status')),
                ('trash', models.CharField(default='0', max_length=40, verbose_name='Trash')),
                ('userno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
